pairinteraction: /travis/pairinteraction/unit_test/cache_test.cpp File Reference
cache_test.cpp File Reference
#include "Cache.h"
#include <boost/test/unit_test.hpp>
#include <thread>
#include <vector>
Macros
#define BOOST_TEST_MODULE Configuration parser test
Functions
BOOST_AUTO_TEST_CASE (cache_test)
BOOST_AUTO_TEST_CASE (smash_test)
BOOST_AUTO_TEST_CASE (parallel_cache_test)
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE Configuration parser test
Definition at line 21 of file cache_test.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (cache_test)
Definition at line 26 of file cache_test.cpp.
References Cache< Key, Element, Hash >::clear(), Cache< Key, Element, Hash >::restore(), and Cache< Key, Element, Hash >::save().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (smash_test)
Definition at line 39 of file cache_test.cpp.
References Cache< Key, Element, Hash >::save().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (parallel_cache_test)
Definition at line 47 of file cache_test.cpp.
References Cache< Key, Element, Hash >::restore(), and Cache< Key, Element, Hash >::save().