pairinteraction: MatrixElementCache Class Reference
MatrixElementCache Class Reference
#include <MatrixElementCache.h>
Public Member Functions
MatrixElementCache ()
Constructors ///////////////////////////////////////////////////.
MatrixElementCache (std::string const &cachedir)
double getElectricDipole (StateOne const &state_row, StateOne const &state_col)
Get matrix elements ////////////////////////////////////////////.
double getElectricMultipole (StateOne const &state_row, StateOne const &state_col, int k)
double getDiamagnetism (StateOne const &state_row, StateOne const &state_col, int k)
double getMagneticDipole (StateOne const &state_row, StateOne const &state_col)
double getElectricMultipole (StateOne const &state_row, StateOne const &state_col, int kappa_radial, int kappa_angular)
double getRadial (StateOne const &state_row, StateOne const &state_col, int kappa)
void precalculateElectricMomentum (const std::vector< StateOne > &basis_one, int q)
void precalculateMagneticMomentum (const std::vector< StateOne > &basis_one, int q)
void precalculateDiamagnetism (const std::vector< StateOne > &basis_one, int k, int q)
void precalculateMultipole (const std::vector< StateOne > &basis_one, int k)
Precalculate matrix elements ///////////////////////////////////.
void precalculateRadial (const std::vector< StateOne > &basis_one, int k)
void setDefectDB (std::string const &path)
const std::string & getDefectDB () const
void setMethod (method_t const &m)
void loadElectricDipoleDB (std::string const &path, std::string const &species)
size_t size ()
Friends
class boost::serialization::access
Method for serialization ///////////////////////////////////////.
Detailed Description
Definition at line 51 of file MatrixElementCache.h.
Constructor & Destructor Documentation
MatrixElementCache() [1/2]
MatrixElementCache::MatrixElementCache ()
Constructors ///////////////////////////////////////////////////.
Definition at line 76 of file MatrixElementCache.cpp.
MatrixElementCache() [2/2]
MatrixElementCache::MatrixElementCache (std::string const & cachedir)
Definition at line 79 of file MatrixElementCache.cpp.
Member Function Documentation
getDefectDB()
const std::string & MatrixElementCache::getDefectDB () const
Definition at line 504 of file MatrixElementCache.cpp.
Referenced by StateOne::getEnergy(), and StateOne::getNStar().
getDiamagnetism()
double MatrixElementCache::getDiamagnetism (StateOne const & state_row, StateOne const & state_col, int k)
Definition at line 353 of file MatrixElementCache.cpp.
References getElectricMultipole().
Referenced by SystemOne::initializeInteraction().
getElectricDipole()
double MatrixElementCache::getElectricDipole (StateOne const & state_row, StateOne const & state_col)
Get matrix elements ////////////////////////////////////////////.
Definition at line 344 of file MatrixElementCache.cpp.
References getElectricMultipole().
Referenced by PerturbativeInteraction::getC3(), PerturbativeInteraction::getC6(), SystemTwo::initializeInteraction(), and SystemOne::initializeInteraction().
getElectricMultipole() [1/2]
double MatrixElementCache::getElectricMultipole (StateOne const & state_row, StateOne const & state_col, int k)
Definition at line 348 of file MatrixElementCache.cpp.
Referenced by getDiamagnetism(), getElectricDipole(), and SystemTwo::initializeInteraction().
getElectricMultipole() [2/2]
double MatrixElementCache::getElectricMultipole (StateOne const & state_row, StateOne const & state_col, int kappa_radial, int kappa_angular)
Definition at line 418 of file MatrixElementCache.cpp.
References elementary_charge, StateOne::getJ(), StateOne::getL(), StateOne::getM(), StateOne::getN(), StateOne::getS(), and StateOne::getSpecies().
getMagneticDipole()
double MatrixElementCache::getMagneticDipole (StateOne const & state_row, StateOne const & state_col)
Definition at line 358 of file MatrixElementCache.cpp.
References bohr_magneton, StateOne::getJ(), StateOne::getL(), StateOne::getM(), StateOne::getN(), StateOne::getS(), StateOne::getSpecies(), gL, and gS.
Referenced by SystemOne::initializeInteraction().
getRadial()
double MatrixElementCache::getRadial (StateOne const & state_row, StateOne const & state_col, int kappa)
Definition at line 477 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), StateOne::getN(), and StateOne::getSpecies().
Referenced by StateTwo::getLeRoyRadius().
loadElectricDipoleDB()
void MatrixElementCache::loadElectricDipoleDB (std::string const & path, std::string const & species)
Definition at line 131 of file MatrixElementCache.cpp.
References au2um.
precalculateDiamagnetism()
void MatrixElementCache::precalculateDiamagnetism (const std::vector< StateOne > & basis_one, int k, int q)
Definition at line 533 of file MatrixElementCache.cpp.
References au2um, utils::get_pid(), NUMEROV, selectionRulesMomentumNew(), selectionRulesMultipoleNew(), and WHITTAKER.
Referenced by SystemOne::initializeInteraction().
precalculateElectricMomentum()
void MatrixElementCache::precalculateElectricMomentum (const std::vector< StateOne > & basis_one, int q)
Definition at line 523 of file MatrixElementCache.cpp.
Referenced by SystemOne::initializeInteraction().
precalculateMagneticMomentum()
void MatrixElementCache::precalculateMagneticMomentum (const std::vector< StateOne > & basis_one, int q)
Definition at line 528 of file MatrixElementCache.cpp.
Referenced by SystemOne::initializeInteraction().
precalculateMultipole()
void MatrixElementCache::precalculateMultipole (const std::vector< StateOne > & basis_one, int k)
Precalculate matrix elements ///////////////////////////////////.
Definition at line 513 of file MatrixElementCache.cpp.
Referenced by SystemTwo::initializeInteraction().
precalculateRadial()
void MatrixElementCache::precalculateRadial (const std::vector< StateOne > & basis_one, int k)
Definition at line 518 of file MatrixElementCache.cpp.
setDefectDB()
void MatrixElementCache::setDefectDB (std::string const & path)
Definition at line 118 of file MatrixElementCache.cpp.
setMethod()
void MatrixElementCache::setMethod (method_t const & m)
Definition at line 126 of file MatrixElementCache.cpp.
size()
size_t MatrixElementCache::size ()
Definition at line 978 of file MatrixElementCache.cpp.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 210 of file MatrixElementCache.h.
The documentation for this class was generated from the following files:
/travis/pairinteraction/MatrixElementCache.h
/travis/pairinteraction/MatrixElementCache.cpp