pairinteraction: HamiltonianOne Class Reference
HamiltonianOne Class Reference
#include <HamiltonianOne.h>
Public Member Functions
HamiltonianOne (const Configuration &config, boost::filesystem::path &path_cache, std::shared_ptr< BasisnamesOne > basis_one)
const Configuration & getConf () const
Public Member Functions inherited from Hamiltonian< BasisnamesOne >
Hamiltonian ()=default
std::shared_ptr< Hamiltonianmatrix > get (size_t idx)
std::shared_ptr< const Hamiltonianmatrix > get (size_t idx) const
std::shared_ptr< const Configuration > getParams (size_t idx) const
size_t size () const
std::shared_ptr< const BasisnamesOne > names () const
void removeUnnecessaryStates (std::vector< bool > &necessary)
Protected Member Functions
void changeToSpherical (double val_x, double val_y, double val_z, double &val_p, double &val_m, double &val_0)
void changeToSpherical (double val_x, double val_y, double val_z, std::complex< double > &val_p, std::complex< double > &val_m, std::complex< double > &val_0)
void configure (const Configuration &config)
void build ()
Additional Inherited Members
Protected Attributes inherited from Hamiltonian< BasisnamesOne >
std::vector< std::shared_ptr< Hamiltonianmatrix > > matrix_diag
std::vector< std::string > matrix_path
std::vector< std::shared_ptr< Configuration > > params
std::shared_ptr< BasisnamesOne > basis
Detailed Description
Definition at line 38 of file HamiltonianOne.h.
Constructor & Destructor Documentation
HamiltonianOne()
HamiltonianOne::HamiltonianOne (const Configuration & config, boost::filesystem::path & path_cache, std::shared_ptr< BasisnamesOne > basis_one)
Definition at line 26 of file HamiltonianOne.cpp.
References Hamiltonian< BasisnamesOne >::basis, build(), and configure().
Member Function Documentation
build()
void HamiltonianOne::build () protected
Definition at line 90 of file HamiltonianOne.cpp.
References Hamiltonianmatrix::addBasis(), Hamiltonianmatrix::addEntries(), Hamiltonian< BasisnamesOne >::basis, changeToSpherical(), Hamiltonianmatrix::compress(), Hamiltonianmatrix::diagonalize(), energy_level(), MatrixElements::getDiamagnetism(), MatrixElements::getElectricMomentum(), MatrixElements::getMagneticMomentum(), Hamiltonianmatrix::load(), Configuration::load_from_json(), Hamiltonian< BasisnamesOne >::matrix_diag, Hamiltonian< BasisnamesOne >::matrix_path, Hamiltonianmatrix::num_basisvectors(), Hamiltonian< BasisnamesOne >::params, MatrixElements::precalculateDiamagnetism(), MatrixElements::precalculateElectricMomentum(), MatrixElements::precalculateMagneticMomentum(), sqlite::statement::prepare(), Hamiltonianmatrix::save(), selectionRulesMomentum(), and selectionRulesMultipole().
Referenced by HamiltonianOne().
changeToSpherical() [1/2]
void HamiltonianOne::changeToSpherical (double val_x, double val_y, double val_z, double & val_p, double & val_m, double & val_0) protected
Definition at line 39 of file HamiltonianOne.cpp.
Referenced by build().
changeToSpherical() [2/2]
void HamiltonianOne::changeToSpherical (double val_x, double val_y, double val_z, std::complex< double > & val_p, std::complex< double > & val_m, std::complex< double > & val_0) protected
Definition at line 51 of file HamiltonianOne.cpp.
configure()
void HamiltonianOne::configure (const Configuration & config) protected
Definition at line 59 of file HamiltonianOne.cpp.
References Hamiltonian< BasisnamesOne >::basis.
Referenced by HamiltonianOne().
getConf()
const Configuration & HamiltonianOne::getConf () const
Definition at line 34 of file HamiltonianOne.cpp.
The documentation for this class was generated from the following files:
/travis/pairinteraction/HamiltonianOne.h
/travis/pairinteraction/HamiltonianOne.cpp