pairinteraction: Hamiltonianmatrix Class Reference
Hamiltonianmatrix Class Reference
#include <Hamiltonianmatrix.h>
Public Member Functions
Hamiltonianmatrix ()
Hamiltonianmatrix (const eigen_sparse_t &entries, const eigen_sparse_t &basis)
Hamiltonianmatrix (size_t szBasis, size_t szEntries)
eigen_sparse_t & entries ()
const eigen_sparse_t & entries () const
eigen_sparse_t & basis ()
const eigen_sparse_t & basis () const
size_t num_basisvectors () const
size_t num_coordinates () const
void addBasis (idx_t row, idx_t col, scalar_t val)
void addEntries (idx_t row, idx_t col, scalar_t val)
void compress (size_t nBasis, size_t nCoordinates)
std::vector< Hamiltonianmatrix > findSubs () const
Hamiltonianmatrix abs () const
Hamiltonianmatrix changeBasis (const eigen_sparse_t &basis) const
void applyCutoff (double cutoff)
void findUnnecessaryStates (std::vector< bool > &isNecessaryCoordinate) const
void removeUnnecessaryBasisvectors (const std::vector< bool > &isNecessaryCoordinate)
void removeUnnecessaryBasisvectors ()
void removeUnnecessaryStates (const std::vector< bool > &isNecessaryCoordinate)
Hamiltonianmatrix getBlock (const std::vector< ptrdiff_t > &indices)
void diagonalize ()
Hamiltonianmatrix & operator+= (const Hamiltonianmatrix &rhs)
Hamiltonianmatrix & operator-= (const Hamiltonianmatrix &rhs)
bytes_t & serialize () override
void doSerialization ()
void deserialize (bytes_t &bytesin) override
void doDeserialization ()
uint64_t hashEntries ()
uint64_t hashBasis ()
void save (const std::string &fname)
bool load (const std::string &fname)
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr>
void mergeComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr>
void mergeComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr>
void splitComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr>
void splitComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
Public Member Functions inherited from Serializable
virtual ~Serializable ()=default
Protected Attributes
eigen_sparse_t entries_
eigen_sparse_t basis_
bytes_t bytes
std::vector< eigen_triplet_t > triplets_basis
std::vector< eigen_triplet_t > triplets_entries
Friends
Hamiltonianmatrix operator+ (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
Hamiltonianmatrix operator- (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
Hamiltonianmatrix operator* (const scalar_t &lhs, Hamiltonianmatrix rhs)
Hamiltonianmatrix operator* (Hamiltonianmatrix lhs, const scalar_t &rhs)
Hamiltonianmatrix combine (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, const std::shared_ptr< BasisnamesTwo > &basis_two, const Symmetry &sym)
void energycutoff (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, std::vector< bool > &necessary)
Detailed Description
Definition at line 40 of file Hamiltonianmatrix.h.
Constructor & Destructor Documentation
Hamiltonianmatrix() [1/3]
Hamiltonianmatrix::Hamiltonianmatrix () default
Referenced by abs(), changeBasis(), and getBlock().
Hamiltonianmatrix() [2/3]
Hamiltonianmatrix::Hamiltonianmatrix (const eigen_sparse_t & entries, const eigen_sparse_t & basis)
Definition at line 27 of file Hamiltonianmatrix.cpp.
Hamiltonianmatrix() [3/3]
Hamiltonianmatrix::Hamiltonianmatrix (size_t szBasis, size_t szEntries)
Definition at line 30 of file Hamiltonianmatrix.cpp.
References triplets_basis, and triplets_entries.
Member Function Documentation
abs()
Hamiltonianmatrix Hamiltonianmatrix::abs () const
Definition at line 76 of file Hamiltonianmatrix.cpp.
References basis_, entries_, and Hamiltonianmatrix().
addBasis()
void Hamiltonianmatrix::addBasis (idx_t row, idx_t col, scalar_t val)
Definition at line 53 of file Hamiltonianmatrix.cpp.
References triplets_basis.
Referenced by HamiltonianOne::build(), and combine().
addEntries()
void Hamiltonianmatrix::addEntries (idx_t row, idx_t col, scalar_t val)
Definition at line 57 of file Hamiltonianmatrix.cpp.
References triplets_entries.
Referenced by HamiltonianOne::build(), and combine().
applyCutoff()
void Hamiltonianmatrix::applyCutoff (double cutoff)
Definition at line 86 of file Hamiltonianmatrix.cpp.
References basis_, bytes, entries_, and num_basisvectors().
basis() [1/2]
eigen_sparse_t & Hamiltonianmatrix::basis ()
Definition at line 42 of file Hamiltonianmatrix.cpp.
References basis_, and bytes.
Referenced by HamiltonianTwo::calculate(), changeBasis(), combine(), diagonalize(), and energycutoff().
basis() [2/2]
const eigen_sparse_t & Hamiltonianmatrix::basis () const
Definition at line 47 of file Hamiltonianmatrix.cpp.
References basis_.
changeBasis()
Hamiltonianmatrix Hamiltonianmatrix::changeBasis (const eigen_sparse_t & basis) const
Definition at line 80 of file Hamiltonianmatrix.cpp.
References basis(), basis_, entries(), entries_, and Hamiltonianmatrix().
Referenced by HamiltonianTwo::calculate().
compress()
void Hamiltonianmatrix::compress (size_t nBasis, size_t nCoordinates)
Definition at line 61 of file Hamiltonianmatrix.cpp.
References basis_, entries_, triplets_basis, and triplets_entries.
Referenced by HamiltonianOne::build(), and combine().
deserialize()
void Hamiltonianmatrix::deserialize (bytes_t & bytesin) override virtual
Implements Serializable.
Definition at line 352 of file Hamiltonianmatrix.cpp.
References bytes, and doDeserialization().
diagonalize()
void Hamiltonianmatrix::diagonalize ()
Definition at line 225 of file Hamiltonianmatrix.cpp.
References basis(), entries(), and num_basisvectors().
Referenced by HamiltonianOne::build(), and HamiltonianTwo::calculate().
doDeserialization()
void Hamiltonianmatrix::doDeserialization ()
Definition at line 357 of file Hamiltonianmatrix.cpp.
References basis_, bytes, complex_not_real, numpy::copy, entries_, Serializer::load(), and mergeComplex().
Referenced by deserialize(), and load().
doSerialization()
void Hamiltonianmatrix::doSerialization ()
Definition at line 286 of file Hamiltonianmatrix.cpp.
References basis_, bytes, complex_not_real, csr_not_csc, entries_, Serializer::save(), and splitComplex().
Referenced by hashBasis(), hashEntries(), save(), and serialize().
entries() [1/2]
eigen_sparse_t & Hamiltonianmatrix::entries ()
Definition at line 35 of file Hamiltonianmatrix.cpp.
References bytes, and entries_.
Referenced by changeBasis(), combine(), diagonalize(), and energycutoff().
entries() [2/2]
const eigen_sparse_t & Hamiltonianmatrix::entries () const
Definition at line 40 of file Hamiltonianmatrix.cpp.
References entries_.
findSubs()
std::vector< Hamiltonianmatrix > Hamiltonianmatrix::findSubs () const
Definition at line 70 of file Hamiltonianmatrix.cpp.
findUnnecessaryStates()
void Hamiltonianmatrix::findUnnecessaryStates (std::vector< bool > & isNecessaryCoordinate) const
Definition at line 110 of file Hamiltonianmatrix.cpp.
References basis_, and num_coordinates().
getBlock()
Hamiltonianmatrix Hamiltonianmatrix::getBlock (const std::vector< ptrdiff_t > & indices)
Definition at line 210 of file Hamiltonianmatrix.cpp.
References basis_, entries_, Hamiltonianmatrix(), and num_basisvectors().
hashBasis()
uint64_t Hamiltonianmatrix::hashBasis ()
Definition at line 428 of file Hamiltonianmatrix.cpp.
References bytes, doSerialization(), and utils::FNV64().
hashEntries()
uint64_t Hamiltonianmatrix::hashEntries ()
Definition at line 422 of file Hamiltonianmatrix.cpp.
References bytes, doSerialization(), and utils::FNV64().
load()
bool Hamiltonianmatrix::load (const std::string & fname)
Definition at line 448 of file Hamiltonianmatrix.cpp.
References bytes, and doDeserialization().
Referenced by HamiltonianOne::build(), and HamiltonianTwo::calculate().
mergeComplex() [1/2]
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix::mergeComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 86 of file Hamiltonianmatrix.h.
Referenced by doDeserialization().
mergeComplex() [2/2]
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix::mergeComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 97 of file Hamiltonianmatrix.h.
num_basisvectors()
size_t Hamiltonianmatrix::num_basisvectors () const
Definition at line 49 of file Hamiltonianmatrix.cpp.
References basis_.
Referenced by applyCutoff(), HamiltonianOne::build(), HamiltonianTwo::calculate(), combine(), diagonalize(), getBlock(), and removeUnnecessaryBasisvectors().
num_coordinates()
size_t Hamiltonianmatrix::num_coordinates () const
Definition at line 51 of file Hamiltonianmatrix.cpp.
References basis_.
Referenced by combine(), energycutoff(), findUnnecessaryStates(), and removeUnnecessaryStates().
operator+=()
Hamiltonianmatrix & Hamiltonianmatrix::operator+= (const Hamiltonianmatrix & rhs)
Definition at line 269 of file Hamiltonianmatrix.cpp.
References bytes, and entries_.
operator-=()
Hamiltonianmatrix & Hamiltonianmatrix::operator-= (const Hamiltonianmatrix & rhs)
Definition at line 275 of file Hamiltonianmatrix.cpp.
References bytes, and entries_.
removeUnnecessaryBasisvectors() [1/2]
void Hamiltonianmatrix::removeUnnecessaryBasisvectors (const std::vector< bool > & isNecessaryCoordinate)
Definition at line 125 of file Hamiltonianmatrix.cpp.
References basis_, bytes, entries_, and num_basisvectors().
Referenced by HamiltonianTwo::calculate().
removeUnnecessaryBasisvectors() [2/2]
void Hamiltonianmatrix::removeUnnecessaryBasisvectors ()
Definition at line 159 of file Hamiltonianmatrix.cpp.
References basis_, bytes, entries_, and num_basisvectors().
removeUnnecessaryStates()
void Hamiltonianmatrix::removeUnnecessaryStates (const std::vector< bool > & isNecessaryCoordinate)
Definition at line 189 of file Hamiltonianmatrix.cpp.
References basis_, bytes, and num_coordinates().
save()
void Hamiltonianmatrix::save (const std::string & fname)
Definition at line 434 of file Hamiltonianmatrix.cpp.
References bytes, and doSerialization().
Referenced by HamiltonianOne::build(), and HamiltonianTwo::calculate().
serialize()
bytes_t & Hamiltonianmatrix::serialize () override virtual
Implements Serializable.
Definition at line 281 of file Hamiltonianmatrix.cpp.
References bytes, and doSerialization().
splitComplex() [1/2]
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix::splitComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 104 of file Hamiltonianmatrix.h.
Referenced by doSerialization().
splitComplex() [2/2]
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix::splitComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 115 of file Hamiltonianmatrix.h.
Friends And Related Function Documentation
combine
Hamiltonianmatrix combine (const Hamiltonianmatrix & lhs, const Hamiltonianmatrix & rhs, const double & deltaE, const std::shared_ptr< BasisnamesTwo > & basis_two, const Symmetry & sym) friend
Definition at line 480 of file Hamiltonianmatrix.cpp.
energycutoff
void energycutoff (const Hamiltonianmatrix & lhs, const Hamiltonianmatrix & rhs, const double & deltaE, std::vector< bool > & necessary) friend
Definition at line 710 of file Hamiltonianmatrix.cpp.
operator* [1/2]
Hamiltonianmatrix operator* (const scalar_t & lhs, Hamiltonianmatrix rhs) friend
Definition at line 257 of file Hamiltonianmatrix.cpp.
operator* [2/2]
Hamiltonianmatrix operator* (Hamiltonianmatrix lhs, const scalar_t & rhs) friend
Definition at line 263 of file Hamiltonianmatrix.cpp.
operator+
Hamiltonianmatrix operator+ (Hamiltonianmatrix lhs, const Hamiltonianmatrix & rhs) friend
Definition at line 245 of file Hamiltonianmatrix.cpp.
operator-
Hamiltonianmatrix operator- (Hamiltonianmatrix lhs, const Hamiltonianmatrix & rhs) friend
Definition at line 251 of file Hamiltonianmatrix.cpp.
Field Documentation
basis_
eigen_sparse_t Hamiltonianmatrix::basis_ protected
Definition at line 123 of file Hamiltonianmatrix.h.
Referenced by abs(), applyCutoff(), basis(), changeBasis(), compress(), doDeserialization(), doSerialization(), findUnnecessaryStates(), getBlock(), num_basisvectors(), num_coordinates(), removeUnnecessaryBasisvectors(), and removeUnnecessaryStates().
bytes
bytes_t Hamiltonianmatrix::bytes protected
Definition at line 124 of file Hamiltonianmatrix.h.
Referenced by applyCutoff(), basis(), deserialize(), doDeserialization(), doSerialization(), entries(), hashBasis(), hashEntries(), load(), operator*(), operator+(), operator+=(), operator-(), operator-=(), removeUnnecessaryBasisvectors(), removeUnnecessaryStates(), save(), and serialize().
entries_
eigen_sparse_t Hamiltonianmatrix::entries_ protected
Definition at line 122 of file Hamiltonianmatrix.h.
Referenced by abs(), applyCutoff(), changeBasis(), compress(), doDeserialization(), doSerialization(), entries(), getBlock(), operator*(), operator+(), operator+=(), operator-(), operator-=(), and removeUnnecessaryBasisvectors().
triplets_basis
std::vector<eigen_triplet_t> Hamiltonianmatrix::triplets_basis protected
Definition at line 125 of file Hamiltonianmatrix.h.
Referenced by addBasis(), compress(), and Hamiltonianmatrix().
triplets_entries
std::vector<eigen_triplet_t> Hamiltonianmatrix::triplets_entries protected
Definition at line 126 of file Hamiltonianmatrix.h.
Referenced by addEntries(), compress(), and Hamiltonianmatrix().
The documentation for this class was generated from the following files:
/travis/pairinteraction/Hamiltonianmatrix.h
/travis/pairinteraction/Hamiltonianmatrix.cpp