pairinteraction: SystemTwo Class Reference
SystemTwo Class Reference
#include <SystemTwo.h>
Public Member Functions
SystemTwo (const SystemOne &b1, const SystemOne &b2, MatrixElementCache &cache)
SystemTwo (const SystemOne &b1, const SystemOne &b2, MatrixElementCache &cache, bool memory_saving)
const std::array< std::string, 2 > & getSpecies ()
std::vector< StateOne > getStatesFirst ()
std::vector< StateOne > getStatesSecond ()
void enableGreenTensor (bool GTboolean)
void setSurfaceDistance (double d)
void setAngle (double a)
void setDistance (double d)
void setDistanceVector (std::array< double, 3 > d)
void setOrder (double o)
void setConservedParityUnderPermutation (parity_t parity)
void setConservedParityUnderInversion (parity_t parity)
void setConservedParityUnderReflection (parity_t parity)
void setConservedMomentaUnderRotation (const std::set< int > &momenta)
void setOneAtomBasisvectors (const std::vector< std::array< size_t, 2 >> &indices)
Public Member Functions inherited from SystemBase< StateTwo >
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const StateTwo &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< StateTwo > &s)
eigen_vector_double_t getOverlap (const StateTwo &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
eigen_vector_double_t getOverlap (const std::vector< StateTwo > &generalizedstates)
eigen_vector_double_t getOverlap (const size_t &state_index)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices)
eigen_vector_double_t getOverlap (const StateTwo &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< StateTwo > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const StateTwo &generalizedstate, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< StateTwo > &generalizedstates, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< StateTwo > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< StateTwo >::type & getStatesMultiIndex ()
eigen_sparse_t & getBasisvectors ()
eigen_sparse_t & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< StateTwo > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< StateTwo > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< StateTwo > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< StateTwo > &system0)
size_t getStateIndex (const StateTwo &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< StateTwo > &searched_states)
size_t getBasisvectorIndex (const StateTwo &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< StateTwo > &searched_states)
void forgetStatemixing ()
scalar_t getHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col)
void setHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col, scalar_t value)
void addHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col, scalar_t value)
Protected Member Functions
void initializeBasis () override
Method that allows base class to initialize Basis //////////////.
void initializeInteraction () override
Method that allows base class to calculate the interaction /////.
void addInteraction () override
Method that allows base class to construct Hamiltonian /////////.
void transformInteraction (const eigen_sparse_t &transformator) override
Method that allows base class to transform the interaction /////.
void deleteInteraction () override
Method that allows base class to delete the interaction ////////.
eigen_sparse_t rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma) override
Methods that allows base class to rotate states ////////////////.
eigen_sparse_t buildStaterotator (double alpha, double beta, double gamma) override
void incorporate (SystemBase< StateTwo > &system) override
Method that allows base class to combine systems ///////////////.
void onStatesChange () override
Methods that allows base class to communicate with subclass ////.
Protected Member Functions inherited from SystemBase< StateTwo >
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const eigen_sparse_t &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const eigen_sparse_t &mat)
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateTwo &state)
bool checkIsQuantumstateValid (const StateTwo &state, bool a)
bool checkIsQuantumstateValid (const StateTwo &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (eigen_sparse_t &transformator)
void applyRightsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
void applyRightsideTransformator (eigen_sparse_t &transformator)
void removeRestrictedStates (F &&checkIsValidEntry)
S createStateFromLabel (const std::string &label) const
Utility methods ////////////////////////////////////////////////.
void range (std::set< V > &rset, V rmin, V rmax)
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Friends
class boost::serialization::access
Method for serialization ///////////////////////////////////////.
Additional Inherited Members
Protected Attributes inherited from SystemBase< StateTwo >
MatrixElementCache & cache
double threshold_for_sqnorm
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< StateTwo > states_to_add
bool memory_saving
bool is_interaction_already_contained
bool is_new_hamiltonian_required
states_set< StateTwo >::type states
eigen_sparse_t basisvectors
eigen_sparse_t hamiltonian
eigen_sparse_t basisvectors_unperturbed_cache
eigen_sparse_t hamiltonian_unperturbed_cache
Detailed Description
Definition at line 35 of file SystemTwo.h.
Constructor & Destructor Documentation
SystemTwo() [1/2]
SystemTwo::SystemTwo (const SystemOne & b1, const SystemOne & b2, MatrixElementCache & cache)
Definition at line 32 of file SystemTwo.cpp.
References ARB, SystemOne::getSpecies(), and NA.
SystemTwo() [2/2]
SystemTwo::SystemTwo (const SystemOne & b1, const SystemOne & b2, MatrixElementCache & cache, bool memory_saving)
Definition at line 40 of file SystemTwo.cpp.
References ARB, SystemOne::getSpecies(), and NA.
Member Function Documentation
addInteraction()
void SystemTwo::addInteraction () override protected virtual
Method that allows base class to construct Hamiltonian /////////.
Implements SystemBase< StateTwo >.
Definition at line 1286 of file SystemTwo.cpp.
References model_potential::g(), and SystemBase< StateTwo >::hamiltonian.
buildStaterotator()
eigen_sparse_t SystemTwo::buildStaterotator (double alpha, double beta, double gamma) override protected virtual
Implements SystemBase< StateTwo >.
Definition at line 1378 of file SystemTwo.cpp.
References SystemBase< StateTwo >::states.
deleteInteraction()
void SystemTwo::deleteInteraction () override protected virtual
Method that allows base class to delete the interaction ////////.
Implements SystemBase< StateTwo >.
Definition at line 1341 of file SystemTwo.cpp.
Referenced by incorporate().
enableGreenTensor()
void SystemTwo::enableGreenTensor (bool GTboolean)
Definition at line 71 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onParameterChange().
Referenced by setDistanceVector(), and setSurfaceDistance().
getSpecies()
const std::array< std::string, 2 > & SystemTwo::getSpecies ()
Definition at line 69 of file SystemTwo.cpp.
getStatesFirst()
std::vector< StateOne > SystemTwo::getStatesFirst ()
Definition at line 50 of file SystemTwo.cpp.
References SystemBase< StateTwo >::buildBasis(), and SystemBase< StateTwo >::states.
Referenced by initializeInteraction().
getStatesSecond()
std::vector< StateOne > SystemTwo::getStatesSecond ()
Definition at line 60 of file SystemTwo.cpp.
References SystemBase< StateTwo >::buildBasis(), and SystemBase< StateTwo >::states.
Referenced by initializeInteraction().
incorporate()
void SystemTwo::incorporate (SystemBase< StateTwo > & system) override protected virtual
Method that allows base class to combine systems ///////////////.
Implements SystemBase< StateTwo >.
Definition at line 1403 of file SystemTwo.cpp.
References ARB, deleteInteraction(), and NA.
initializeBasis()
void SystemTwo::initializeBasis () override protected virtual
Method that allows base class to initialize Basis //////////////.
Restrict one atom states to the allowed quantum numbers ////////
Check whether the single atom states fit to the symmetries /////
Check which basis vectors contain artificial states ////////////
Build two atom states //////////////////////////////////////////
Combine one atom states ////////////////////////////////////////
Loop over user-defined states //////////////////////////////////
Build data /////////////////////////////////////////////////////
Remove vectors with too small norm /////////////////////////////
Remove states that barely occur ////////////////////////////////
Implements SystemBase< StateTwo >.
Definition at line 172 of file SystemTwo.cpp.
References SystemBase< StateTwo >::applyRightsideTransformator(), ARB, SystemBase< StateTwo >::basisvectors, SystemBase< StateTwo >::cache, SystemBase< StateTwo >::checkIsEnergyValid(), SystemBase< T >::diagonalize(), EVEN, SystemBase< T >::getBasisvectors(), SystemBase< T >::getHamiltonian(), StateOne::getJ(), StateOne::getL(), StateOne::getM(), SystemBase< T >::getNumBasisvectors(), SystemBase< T >::getNumStates(), StateOne::getReflected(), SystemBase< T >::getStatesMultiIndex(), SystemBase< StateTwo >::hamiltonian, enumerated_state< T >::idx, NA, ODD, SystemBase< StateTwo >::range_j, SystemBase< StateTwo >::range_l, SystemBase< StateTwo >::range_m, SystemBase< StateTwo >::range_n, SystemBase< StateTwo >::removeRestrictedStates(), SystemBase< T >::restrictJ(), SystemBase< T >::restrictL(), SystemBase< T >::restrictM(), SystemBase< T >::restrictN(), SystemBase< StateTwo >::states, SystemBase< StateTwo >::states_to_add, and SystemBase< StateTwo >::threshold_for_sqnorm.
initializeInteraction()
void SystemTwo::initializeInteraction () override protected virtual
Method that allows base class to calculate the interaction /////.
Prepare the calculation of the interaction /////////////////////
Generate the interaction in the canonical basis ////////////////
Build and transform the interaction to the used basis //////////
Implements SystemBase< StateTwo >.
Definition at line 614 of file SystemTwo.cpp.
References GreenTensor::addSurface(), SystemBase< StateTwo >::basisvectors, SystemBase< StateTwo >::cache, coulombs_constant, GreenTensor::getDDTensor(), GreenTensor::getDQTensor(), MatrixElementCache::getElectricDipole(), MatrixElementCache::getElectricMultipole(), GreenTensor::getQDTensor(), getStatesFirst(), getStatesSecond(), MatrixElementCache::precalculateMultipole(), selectionRulesMultipoleNew(), and SystemBase< StateTwo >::states.
onStatesChange()
void SystemTwo::onStatesChange () override protected virtual
Methods that allows base class to communicate with subclass ////.
Reimplemented from SystemBase< StateTwo >.
Definition at line 1467 of file SystemTwo.cpp.
References ARB, au2um, SystemBase< StateTwo >::cache, StateTwo::getNStar(), NA, and SystemBase< StateTwo >::states.
rotateStates()
eigen_sparse_t SystemTwo::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) override protected virtual
Methods that allows base class to rotate states ////////////////.
Implements SystemBase< StateTwo >.
Definition at line 1353 of file SystemTwo.cpp.
References SystemBase< StateTwo >::states.
setAngle()
void SystemTwo::setAngle (double a)
Definition at line 107 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onParameterChange().
Referenced by BOOST_FIXTURE_TEST_CASE().
setConservedMomentaUnderRotation()
void SystemTwo::setConservedMomentaUnderRotation (const std::set< int > & momenta)
Definition at line 142 of file SystemTwo.cpp.
References ARB, and SystemBase< StateTwo >::onSymmetryChange().
setConservedParityUnderInversion()
void SystemTwo::setConservedParityUnderInversion (parity_t parity)
Definition at line 124 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onSymmetryChange().
setConservedParityUnderPermutation()
void SystemTwo::setConservedParityUnderPermutation (parity_t parity)
Definition at line 119 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onSymmetryChange().
Referenced by BOOST_FIXTURE_TEST_CASE().
setConservedParityUnderReflection()
void SystemTwo::setConservedParityUnderReflection (parity_t parity)
Definition at line 129 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onSymmetryChange().
setDistance()
void SystemTwo::setDistance (double d)
Definition at line 88 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onParameterChange().
Referenced by BOOST_FIXTURE_TEST_CASE().
setDistanceVector()
void SystemTwo::setDistanceVector (std::array< double, 3 > d)
Definition at line 96 of file SystemTwo.cpp.
References enableGreenTensor(), and SystemBase< StateTwo >::onParameterChange().
setOneAtomBasisvectors()
void SystemTwo::setOneAtomBasisvectors (const std::vector< std::array< size_t, 2 >> & indices)
Definition at line 155 of file SystemTwo.cpp.
setOrder()
void SystemTwo::setOrder (double o)
Definition at line 114 of file SystemTwo.cpp.
References SystemBase< StateTwo >::onParameterChange().
setSurfaceDistance()
void SystemTwo::setSurfaceDistance (double d)
Definition at line 80 of file SystemTwo.cpp.
References enableGreenTensor(), and SystemBase< StateTwo >::onParameterChange().
transformInteraction()
void SystemTwo::transformInteraction (const eigen_sparse_t & transformator) override protected virtual
Method that allows base class to transform the interaction /////.
Implements SystemBase< StateTwo >.
Definition at line 1319 of file SystemTwo.cpp.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 170 of file SystemTwo.h.
The documentation for this class was generated from the following files:
/travis/pairinteraction/SystemTwo.h
/travis/pairinteraction/SystemTwo.cpp