pairinteraction: SystemOne Class Reference
SystemOne Class Reference
#include <SystemOne.h>
Public Member Functions
SystemOne (std::string species, MatrixElementCache &cache)
SystemOne (std::string species, MatrixElementCache &cache, bool memory_saving)
const std::string & getSpecies () const
void setEfield (std::array< double, 3 > field)
void setBfield (std::array< double, 3 > field)
void setEfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void setBfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void setEfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
void setBfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
void enableDiamagnetism (bool enable)
void setConservedParityUnderReflection (parity_t parity)
void setConservedMomentaUnderRotation (const std::set< float > &momenta)
Public Member Functions inherited from SystemBase< StateOne >
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const StateOne &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< StateOne > &s)
eigen_vector_double_t getOverlap (const StateOne &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
eigen_vector_double_t getOverlap (const std::vector< StateOne > &generalizedstates)
eigen_vector_double_t getOverlap (const size_t &state_index)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices)
eigen_vector_double_t getOverlap (const StateOne &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< StateOne > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const StateOne &generalizedstate, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< StateOne > &generalizedstates, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< StateOne > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< StateOne >::type & getStatesMultiIndex ()
eigen_sparse_t & getBasisvectors ()
eigen_sparse_t & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< StateOne > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< StateOne > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< StateOne > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< StateOne > &system0)
size_t getStateIndex (const StateOne &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< StateOne > &searched_states)
size_t getBasisvectorIndex (const StateOne &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< StateOne > &searched_states)
void forgetStatemixing ()
scalar_t getHamiltonianEntry (const StateOne &state_row, const StateOne &state_col)
void setHamiltonianEntry (const StateOne &state_row, const StateOne &state_col, scalar_t value)
void addHamiltonianEntry (const StateOne &state_row, const StateOne &state_col, scalar_t value)
Protected Member Functions
void initializeBasis () override
Method that allows base class to initialize Basis //////////////.
void initializeInteraction () override
Method that allows base class to calculate the interaction /////.
void addInteraction () override
Method that allows base class to construct Hamiltonian /////////.
void transformInteraction (const eigen_sparse_t &transformator) override
Method that allows base class to transform the interaction /////.
void deleteInteraction () override
Method that allows base class to delete the interaction ////////.
eigen_sparse_t rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma) override
Methods that allows base class to rotate states ////////////////.
eigen_sparse_t buildStaterotator (double alpha, double beta, double gamma) override
void incorporate (SystemBase< StateOne > &system) override
Method that allows base class to combine systems ///////////////.
Protected Member Functions inherited from SystemBase< StateOne >
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
virtual void onStatesChange ()
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const eigen_sparse_t &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const eigen_sparse_t &mat)
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateOne &state)
bool checkIsQuantumstateValid (const StateOne &state, bool a)
bool checkIsQuantumstateValid (const StateOne &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (eigen_sparse_t &transformator)
void applyRightsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
void applyRightsideTransformator (eigen_sparse_t &transformator)
void removeRestrictedStates (F &&checkIsValidEntry)
S createStateFromLabel (const std::string &label) const
Utility methods ////////////////////////////////////////////////.
void range (std::set< V > &rset, V rmin, V rmax)
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Friends
class boost::serialization::access
Method for serialization ///////////////////////////////////////.
Additional Inherited Members
Protected Attributes inherited from SystemBase< StateOne >
MatrixElementCache & cache
double threshold_for_sqnorm
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< StateOne > states_to_add
bool memory_saving
bool is_interaction_already_contained
bool is_new_hamiltonian_required
states_set< StateOne >::type states
eigen_sparse_t basisvectors
eigen_sparse_t hamiltonian
eigen_sparse_t basisvectors_unperturbed_cache
eigen_sparse_t hamiltonian_unperturbed_cache
Detailed Description
Definition at line 44 of file SystemOne.h.
Constructor & Destructor Documentation
SystemOne() [1/2]
SystemOne::SystemOne (std::string species, MatrixElementCache & cache)
Definition at line 33 of file SystemOne.cpp.
References ARB, and NA.
SystemOne() [2/2]
SystemOne::SystemOne (std::string species, MatrixElementCache & cache, bool memory_saving)
Definition at line 37 of file SystemOne.cpp.
References ARB, and NA.
Member Function Documentation
addInteraction()
void SystemOne::addInteraction () override protected virtual
Method that allows base class to construct Hamiltonian /////////.
Implements SystemBase< StateOne >.
Definition at line 481 of file SystemOne.cpp.
References SystemBase< StateOne >::hamiltonian.
buildStaterotator()
eigen_sparse_t SystemOne::buildStaterotator (double alpha, double beta, double gamma) override protected virtual
Implements SystemBase< StateOne >.
Definition at line 582 of file SystemOne.cpp.
References SystemBase< StateOne >::states.
deleteInteraction()
void SystemOne::deleteInteraction () override protected virtual
Method that allows base class to delete the interaction ////////.
Implements SystemBase< StateOne >.
Definition at line 548 of file SystemOne.cpp.
Referenced by incorporate().
enableDiamagnetism()
void SystemOne::enableDiamagnetism (bool enable)
Definition at line 91 of file SystemOne.cpp.
References SystemBase< StateOne >::onParameterChange().
getSpecies()
const std::string & SystemOne::getSpecies () const
Definition at line 42 of file SystemOne.cpp.
Referenced by SystemTwo::SystemTwo().
incorporate()
void SystemOne::incorporate (SystemBase< StateOne > & system) override protected virtual
Method that allows base class to combine systems ///////////////.
Implements SystemBase< StateOne >.
Definition at line 607 of file SystemOne.cpp.
References ARB, SystemBase< StateOne >::buildRotator(), deleteInteraction(), EVEN, StateOne::getJ(), StateOne::getL(), StateOne::getM(), StateOne::getReflected(), NA, and SystemBase< StateOne >::states.
initializeBasis()
void SystemOne::initializeBasis () override protected virtual
Method that allows base class to initialize Basis //////////////.
Build one atom states //////////////////////////////////////////
Loop over specified quantum numbers ////////////////////////////
Loop over user-defined states //////////////////////////////////
Build data /////////////////////////////////////////////////////
Implements SystemBase< StateOne >.
Definition at line 122 of file SystemOne.cpp.
References ARB, SystemBase< StateOne >::basisvectors, SystemBase< StateOne >::cache, SystemBase< StateOne >::checkIsEnergyValid(), SystemBase< StateOne >::energy_max, SystemBase< StateOne >::energy_min, StateOne::getEnergy(), StateOne::getM(), SystemBase< StateOne >::hamiltonian, NA, SystemBase< StateOne >::range(), SystemBase< StateOne >::range_j, SystemBase< StateOne >::range_l, SystemBase< StateOne >::range_m, SystemBase< StateOne >::range_n, SystemBase< StateOne >::states, and SystemBase< StateOne >::states_to_add.
initializeInteraction()
void SystemOne::initializeInteraction () override protected virtual
Method that allows base class to calculate the interaction /////.
Prepare the calculation of the interaction /////////////////////
Calculate the interaction in the canonical basis ///////////////
Build and transform the interaction to the used basis //////////
Implements SystemBase< StateOne >.
Definition at line 294 of file SystemOne.cpp.
References SystemBase< StateOne >::basisvectors, SystemBase< StateOne >::cache, electron_rest_mass, MatrixElementCache::getDiamagnetism(), MatrixElementCache::getElectricDipole(), MatrixElementCache::getMagneticDipole(), SystemBase< StateOne >::getStates(), MatrixElementCache::precalculateDiamagnetism(), MatrixElementCache::precalculateElectricMomentum(), MatrixElementCache::precalculateMagneticMomentum(), selectionRulesMomentumNew(), selectionRulesMultipoleNew(), and SystemBase< StateOne >::states.
rotateStates()
eigen_sparse_t SystemOne::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) override protected virtual
Methods that allows base class to rotate states ////////////////.
Implements SystemBase< StateOne >.
Definition at line 558 of file SystemOne.cpp.
References SystemBase< StateOne >::states.
setBfield() [1/3]
void SystemOne::setBfield (std::array< double, 3 > field)
Definition at line 52 of file SystemOne.cpp.
References SystemBase< StateOne >::onParameterChange().
Referenced by setBfield().
setBfield() [2/3]
void SystemOne::setBfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 75 of file SystemOne.cpp.
References setBfield().
setBfield() [3/3]
void SystemOne::setBfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
Definition at line 86 of file SystemOne.cpp.
References setBfield().
setConservedMomentaUnderRotation()
void SystemOne::setConservedMomentaUnderRotation (const std::set< float > & momenta)
Definition at line 105 of file SystemOne.cpp.
References ARB, and SystemBase< StateOne >::onSymmetryChange().
setConservedParityUnderReflection()
void SystemOne::setConservedParityUnderReflection (parity_t parity)
Definition at line 96 of file SystemOne.cpp.
References SystemBase< StateOne >::onSymmetryChange().
setEfield() [1/3]
void SystemOne::setEfield (std::array< double, 3 > field)
Definition at line 44 of file SystemOne.cpp.
References SystemBase< StateOne >::onParameterChange().
Referenced by setEfield().
setEfield() [2/3]
void SystemOne::setEfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 69 of file SystemOne.cpp.
References setEfield().
setEfield() [3/3]
void SystemOne::setEfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
Definition at line 81 of file SystemOne.cpp.
References setEfield().
transformInteraction()
void SystemOne::transformInteraction (const eigen_sparse_t & transformator) override protected virtual
Method that allows base class to transform the interaction /////.
Implements SystemBase< StateOne >.
Definition at line 532 of file SystemOne.cpp.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 155 of file SystemOne.h.
The documentation for this class was generated from the following files:
/travis/pairinteraction/SystemOne.h
/travis/pairinteraction/SystemOne.cpp