pairinteraction: SystemBase< T > Class Template Reference
SystemBase< T > Class Template Reference abstract
#include <SystemBase.h>
Public Member Functions
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const T &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< T > &s)
eigen_vector_double_t getOverlap (const T &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
eigen_vector_double_t getOverlap (const std::vector< T > &generalizedstates)
eigen_vector_double_t getOverlap (const size_t &state_index)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices)
eigen_vector_double_t getOverlap (const T &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< T > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
eigen_vector_double_t getOverlap (const T &generalizedstate, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< T > &generalizedstates, double alpha, double beta, double gamma)
eigen_vector_double_t getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< T > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< T >::type & getStatesMultiIndex ()
eigen_sparse_t & getBasisvectors ()
eigen_sparse_t & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< T > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< T > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< T > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< T > &system0)
size_t getStateIndex (const T &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< T > &searched_states)
size_t getBasisvectorIndex (const T &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< T > &searched_states)
void forgetStatemixing ()
scalar_t getHamiltonianEntry (const T &state_row, const T &state_col)
void setHamiltonianEntry (const T &state_row, const T &state_col, scalar_t value)
void addHamiltonianEntry (const T &state_row, const T &state_col, scalar_t value)
Protected Member Functions
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
virtual void initializeBasis ()=0
virtual void initializeInteraction ()=0
virtual void transformInteraction (const eigen_sparse_t &transformator)=0
virtual void addInteraction ()=0
virtual void deleteInteraction ()=0
virtual eigen_sparse_t rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)=0
virtual eigen_sparse_t buildStaterotator (double alpha, double beta, double gamma)=0
virtual void incorporate (SystemBase< T > &system)=0
virtual void onStatesChange ()
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const eigen_sparse_t &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const eigen_sparse_t &mat)
template<class V >
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const T &state)
bool checkIsQuantumstateValid (const T &state, bool a)
bool checkIsQuantumstateValid (const T &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (eigen_sparse_t &transformator)
void applyRightsideTransformator (std::vector< eigen_triplet_t > &triplets_transformator)
void applyRightsideTransformator (eigen_sparse_t &transformator)
template<typename F >
void removeRestrictedStates (F &&checkIsValidEntry)
template<class S >
S createStateFromLabel (const std::string &label) const
Utility methods ////////////////////////////////////////////////.
template<class V >
void range (std::set< V > &rset, V rmin, V rmax)
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Protected Attributes
MatrixElementCache & cache
double threshold_for_sqnorm
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< T > states_to_add
bool memory_saving
bool is_interaction_already_contained
bool is_new_hamiltonian_required
states_set< T >::type states
eigen_sparse_t basisvectors
eigen_sparse_t hamiltonian
eigen_sparse_t basisvectors_unperturbed_cache
eigen_sparse_t hamiltonian_unperturbed_cache
Friends
class boost::serialization::access
Method for serialization ///////////////////////////////////////.
Detailed Description
template<class T>
class SystemBase< T >
Definition at line 110 of file SystemBase.h.
Constructor & Destructor Documentation
~SystemBase()
template<class T> virtual SystemBase< T >::~SystemBase () virtual default
SystemBase() [1/2]
template<class T> SystemBase< T >::SystemBase (MatrixElementCache & cache) inline protected
Definition at line 1205 of file SystemBase.h.
SystemBase() [2/2]
template<class T> SystemBase< T >::SystemBase (MatrixElementCache & cache, bool memory_saving) inline protected
Definition at line 1211 of file SystemBase.h.
Member Function Documentation
add()
template<class T> void SystemBase< T >::add (SystemBase< T > & system) inline
Definition at line 761 of file SystemBase.h.
addHamiltonianEntry()
template<class T> void SystemBase< T >::addHamiltonianEntry (const T & state_row, const T & state_col, scalar_t value) inline
Definition at line 1187 of file SystemBase.h.
addInteraction()
template<class T> virtual void SystemBase< T >::addInteraction () protected pure virtual
Implemented in SystemOne, and SystemTwo.
addStates() [1/2]
template<class T> void SystemBase< T >::addStates (const T & s) inline
Method for adding user-defined states //////////////////////////.
Definition at line 145 of file SystemBase.h.
addStates() [2/2]
template<class T> void SystemBase< T >::addStates (const std::set< T > & s) inline
Definition at line 147 of file SystemBase.h.
applyLeftsideTransformator() [1/2]
template<class T> void SystemBase< T >::applyLeftsideTransformator (std::vector< eigen_triplet_t > & triplets_transformator) inline protected
Helper methods to change the set of basis vectors //////////////.
Definition at line 1363 of file SystemBase.h.
applyLeftsideTransformator() [2/2]
template<class T> void SystemBase< T >::applyLeftsideTransformator (eigen_sparse_t & transformator) inline protected
Definition at line 1370 of file SystemBase.h.
applyRightsideTransformator() [1/2]
template<class T> void SystemBase< T >::applyRightsideTransformator (std::vector< eigen_triplet_t > & triplets_transformator) inline protected
Definition at line 1378 of file SystemBase.h.
applyRightsideTransformator() [2/2]
template<class T> void SystemBase< T >::applyRightsideTransformator (eigen_sparse_t & transformator) inline protected
Definition at line 1385 of file SystemBase.h.
applySchriefferWolffTransformation()
template<class T> void SystemBase< T >::applySchriefferWolffTransformation (SystemBase< T > & system0) inline
Definition at line 900 of file SystemBase.h.
buildBasis()
template<class T> void SystemBase< T >::buildBasis () inline
Definition at line 486 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add(), and SystemBase< StateTwo >::getConnections().
buildHamiltonian()
template<class T> void SystemBase< T >::buildHamiltonian () inline
Methods to build, transform, and destroy the system ////////////.
Definition at line 436 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::applySchriefferWolffTransformation().
buildInteraction()
template<class T> void SystemBase< T >::buildInteraction () inline
Definition at line 477 of file SystemBase.h.
buildRotator() [1/2]
template<class T> Eigen::Matrix<double, 3, 3> SystemBase< T >::buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline protected
Definition at line 1451 of file SystemBase.h.
buildRotator() [2/2]
template<class T> Eigen::Matrix<double, 3, 3> SystemBase< T >::buildRotator (const double & alpha, const double & beta, const double & gamma) inline protected
Definition at line 1468 of file SystemBase.h.
buildStaterotator()
template<class T> virtual eigen_sparse_t SystemBase< T >::buildStaterotator (double alpha, double beta, double gamma) protected pure virtual
Implemented in SystemOne, and SystemTwo.
canonicalize()
template<class T> void SystemBase< T >::canonicalize () inline
Definition at line 681 of file SystemBase.h.
checkIsDiagonal()
template<class T> bool SystemBase< T >::checkIsDiagonal (const eigen_sparse_t & mat) inline protected
Helper methods to check diagonality and unitarity of a matrix //.
Definition at line 1283 of file SystemBase.h.
checkIsEnergyValid()
template<class T> bool SystemBase< T >::checkIsEnergyValid (double e) inline protected
Definition at line 1352 of file SystemBase.h.
checkIsQuantumnumberValid()
template<class T> template<class V > bool SystemBase< T >::checkIsQuantumnumberValid (V q, std::set< V > range_q) inline protected
Helper methods to check the validity of states /////////////////.
Definition at line 1323 of file SystemBase.h.
checkIsQuantumstateValid() [1/3]
template<class T> bool SystemBase< T >::checkIsQuantumstateValid (const T & state) inline protected
Definition at line 1327 of file SystemBase.h.
checkIsQuantumstateValid() [2/3]
template<class T> bool SystemBase< T >::checkIsQuantumstateValid (const T & state, bool a) inline protected
Definition at line 1331 of file SystemBase.h.
checkIsQuantumstateValid() [3/3]
template<class T> bool SystemBase< T >::checkIsQuantumstateValid (const T & state, std::array< bool, 2 > a) inline protected
Definition at line 1339 of file SystemBase.h.
checkIsUnitary()
template<class T> bool SystemBase< T >::checkIsUnitary (const eigen_sparse_t & mat) inline protected
Definition at line 1297 of file SystemBase.h.
constrainBasisvectors()
template<class T> void SystemBase< T >::constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors) inline
Definition at line 872 of file SystemBase.h.
createStateFromLabel()
template<class T> template<class S > S SystemBase< T >::createStateFromLabel (const std::string & label) const protected
Utility methods ////////////////////////////////////////////////.
deleteInteraction()
template<class T> virtual void SystemBase< T >::deleteInteraction () protected pure virtual
Implemented in SystemOne, and SystemTwo.
diagonalize() [1/4]
template<class T> void SystemBase< T >::diagonalize (double energy_lower_bound, double energy_upper_bound) inline
Definition at line 525 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and SystemTwo::initializeBasis().
diagonalize() [2/4]
template<class T> void SystemBase< T >::diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold) inline
Definition at line 529 of file SystemBase.h.
diagonalize() [3/4]
template<class T> void SystemBase< T >::diagonalize () inline
Definition at line 646 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::diagonalize().
diagonalize() [4/4]
template<class T> void SystemBase< T >::diagonalize (double threshold) inline
Definition at line 648 of file SystemBase.h.
forgetStatemixing()
template<class T> void SystemBase< T >::forgetStatemixing () inline
Definition at line 1135 of file SystemBase.h.
getBasisvectorIndex() [1/2]
template<class T> size_t SystemBase< T >::getBasisvectorIndex (const T & searched_state) inline
Definition at line 1050 of file SystemBase.h.
getBasisvectorIndex() [2/2]
template<class T> std::vector<size_t> SystemBase< T >::getBasisvectorIndex (const std::vector< T > & searched_states) inline
Definition at line 1072 of file SystemBase.h.
getBasisvectors()
template<class T> eigen_sparse_t& SystemBase< T >::getBasisvectors () inline
Definition at line 293 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and SystemTwo::initializeBasis().
getConnections()
template<class T> std::array<std::vector<size_t>, 2> SystemBase< T >::getConnections (SystemBase< T > & system_to, double threshold) inline
Definition at line 357 of file SystemBase.h.
getEulerAngles()
template<class T> Eigen::Matrix<double, 3, 1> SystemBase< T >::getEulerAngles (const std::array< double, 3 > & to_z_axis, const std::array< double, 3 > & to_y_axis) inline protected
Definition at line 1479 of file SystemBase.h.
getHamiltonian()
template<class T> eigen_sparse_t& SystemBase< T >::getHamiltonian () inline
Definition at line 298 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and SystemTwo::initializeBasis().
getHamiltonianEntry()
template<class T> scalar_t SystemBase< T >::getHamiltonianEntry (const T & state_row, const T & state_col) inline
Definition at line 1159 of file SystemBase.h.
getMainStates()
template<class T> std::vector<T> SystemBase< T >::getMainStates () inline
Definition at line 332 of file SystemBase.h.
getNumBasisvectors()
template<class T> size_t SystemBase< T >::getNumBasisvectors () inline
Definition at line 303 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and SystemTwo::initializeBasis().
getNumStates()
template<class T> size_t SystemBase< T >::getNumStates () inline
Definition at line 318 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and SystemTwo::initializeBasis().
getOverlap() [1/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const T & generalizedstate) inline
Methods to get overlaps ////////////////////////////////////////.
Definition at line 156 of file SystemBase.h.
getOverlap() [2/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< T > & generalizedstates) inline
Definition at line 160 of file SystemBase.h.
getOverlap() [3/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const size_t & state_index) inline
Definition at line 164 of file SystemBase.h.
getOverlap() [4/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< size_t > & states_indices) inline
Definition at line 168 of file SystemBase.h.
getOverlap() [5/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const T & generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline
Definition at line 172 of file SystemBase.h.
getOverlap() [6/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< T > & generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline
Definition at line 178 of file SystemBase.h.
getOverlap() [7/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const size_t & state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline
Definition at line 185 of file SystemBase.h.
getOverlap() [8/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< size_t > & states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline
Definition at line 191 of file SystemBase.h.
getOverlap() [9/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const T & generalizedstate, double alpha, double beta, double gamma) inline
Definition at line 198 of file SystemBase.h.
getOverlap() [10/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const size_t & state_index, double alpha, double beta, double gamma) inline
Definition at line 204 of file SystemBase.h.
getOverlap() [11/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< T > & generalizedstates, double alpha, double beta, double gamma) inline
Definition at line 210 of file SystemBase.h.
getOverlap() [12/12]
template<class T> eigen_vector_double_t SystemBase< T >::getOverlap (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) inline
Definition at line 239 of file SystemBase.h.
getStateIndex() [1/2]
template<class T> size_t SystemBase< T >::getStateIndex (const T & searched_state) inline
Methods to manipulate entries of the Hamiltonian ///////////////.
Definition at line 1014 of file SystemBase.h.
getStateIndex() [2/2]
template<class T> std::vector<size_t> SystemBase< T >::getStateIndex (const std::vector< T > & searched_states) inline
Definition at line 1029 of file SystemBase.h.
getStates()
template<class T> std::vector<T> SystemBase< T >::getStates () inline
Methods to get properties of the system ////////////////////////.
Definition at line 278 of file SystemBase.h.
getStatesMultiIndex()
template<class T> const states_set<T>::type& SystemBase< T >::getStatesMultiIndex () inline
Definition at line 289 of file SystemBase.h.
Referenced by SystemTwo::initializeBasis().
incorporate()
template<class T> virtual void SystemBase< T >::incorporate (SystemBase< T > & system) protected pure virtual
Implemented in SystemOne, and SystemTwo.
initializeBasis()
template<class T> virtual void SystemBase< T >::initializeBasis () protected pure virtual
Implemented in SystemOne, and SystemTwo.
initializeInteraction()
template<class T> virtual void SystemBase< T >::initializeInteraction () protected pure virtual
Implemented in SystemOne, and SystemTwo.
onParameterChange()
template<class T> void SystemBase< T >::onParameterChange () inline protected
Helper method that shoul be called by the derived classes //////.
Definition at line 1254 of file SystemBase.h.
onStatesChange()
template<class T> virtual void SystemBase< T >::onStatesChange () inline protected virtual
Reimplemented in SystemTwo.
Definition at line 1229 of file SystemBase.h.
onSymmetryChange()
template<class T> void SystemBase< T >::onSymmetryChange () inline protected
Definition at line 1272 of file SystemBase.h.
range()
template<class T> template<class V > void SystemBase< T >::range (std::set< V > & rset, V rmin, V rmax) inline protected
Definition at line 1444 of file SystemBase.h.
removeRestrictedStates()
template<class T> template<typename F > void SystemBase< T >::removeRestrictedStates (F && checkIsValidEntry) inline protected
Definition at line 1406 of file SystemBase.h.
restrictEnergy()
template<class T> void SystemBase< T >::restrictEnergy (double e_min, double e_max) inline
Methods to restrict the number of states inside the basis //////.
Definition at line 120 of file SystemBase.h.
Referenced by BOOST_FIXTURE_TEST_CASE().
restrictJ() [1/2]
template<class T> void SystemBase< T >::restrictJ (float j_min, float j_max) inline
Definition at line 133 of file SystemBase.h.
Referenced by SystemTwo::initializeBasis().
restrictJ() [2/2]
template<class T> void SystemBase< T >::restrictJ (std::set< float > j) inline
Definition at line 135 of file SystemBase.h.
restrictL() [1/2]
template<class T> void SystemBase< T >::restrictL (int l_min, int l_max) inline
Definition at line 129 of file SystemBase.h.
Referenced by SystemTwo::initializeBasis().
restrictL() [2/2]
template<class T> void SystemBase< T >::restrictL (std::set< int > l) inline
Definition at line 131 of file SystemBase.h.
restrictM() [1/2]
template<class T> void SystemBase< T >::restrictM (float m_min, float m_max) inline
Definition at line 137 of file SystemBase.h.
Referenced by SystemTwo::initializeBasis().
restrictM() [2/2]
template<class T> void SystemBase< T >::restrictM (std::set< float > m) inline
Definition at line 139 of file SystemBase.h.
restrictN() [1/2]
template<class T> void SystemBase< T >::restrictN (int n_min, int n_max) inline
Definition at line 125 of file SystemBase.h.
Referenced by SystemTwo::initializeBasis().
restrictN() [2/2]
template<class T> void SystemBase< T >::restrictN (std::set< int > n) inline
Definition at line 127 of file SystemBase.h.
rotate() [1/2]
template<class T> void SystemBase< T >::rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) inline
Definition at line 738 of file SystemBase.h.
rotate() [2/2]
template<class T> void SystemBase< T >::rotate (double alpha, double beta, double gamma) inline
Definition at line 743 of file SystemBase.h.
rotateStates()
template<class T> virtual eigen_sparse_t SystemBase< T >::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) protected pure virtual
Implemented in SystemOne, and SystemTwo.
setHamiltonianEntry()
template<class T> void SystemBase< T >::setHamiltonianEntry (const T & state_row, const T & state_col, scalar_t value) inline
Definition at line 1168 of file SystemBase.h.
setMinimalNorm()
template<class T> void SystemBase< T >::setMinimalNorm (const double & threshold) inline
Definition at line 114 of file SystemBase.h.
transformInteraction()
template<class T> virtual void SystemBase< T >::transformInteraction (const eigen_sparse_t & transformator) protected pure virtual
Implemented in SystemOne, and SystemTwo.
unitarize()
template<class T> void SystemBase< T >::unitarize () inline
Definition at line 693 of file SystemBase.h.
Friends And Related Function Documentation
boost::serialization::access
template<class T> friend class boost::serialization::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 1599 of file SystemBase.h.
Field Documentation
basisvectors
template<class T> eigen_sparse_t SystemBase< T >::basisvectors protected
Definition at line 1245 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add(), SystemBase< StateTwo >::applySchriefferWolffTransformation(), and SystemBase< StateTwo >::getConnections().
basisvectors_unperturbed_cache
template<class T> eigen_sparse_t SystemBase< T >::basisvectors_unperturbed_cache protected
Definition at line 1247 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add().
cache
template<class T> MatrixElementCache& SystemBase< T >::cache protected
Definition at line 1229 of file SystemBase.h.
energy_max
template<class T> double SystemBase< T >::energy_max protected
Definition at line 1235 of file SystemBase.h.
energy_min
template<class T> double SystemBase< T >::energy_min protected
Definition at line 1235 of file SystemBase.h.
hamiltonian
template<class T> eigen_sparse_t SystemBase< T >::hamiltonian protected
Definition at line 1246 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add(), and SystemBase< StateTwo >::applySchriefferWolffTransformation().
hamiltonian_unperturbed_cache
template<class T> eigen_sparse_t SystemBase< T >::hamiltonian_unperturbed_cache protected
Definition at line 1248 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add().
is_interaction_already_contained
template<class T> bool SystemBase< T >::is_interaction_already_contained protected
Definition at line 1241 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add().
is_new_hamiltonian_required
template<class T> bool SystemBase< T >::is_new_hamiltonian_required protected
Definition at line 1242 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add().
memory_saving
template<class T> bool SystemBase< T >::memory_saving protected
Definition at line 1240 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add().
range_j
template<class T> std::set<float> SystemBase< T >::range_j protected
Definition at line 1237 of file SystemBase.h.
range_l
template<class T> std::set<int> SystemBase< T >::range_l protected
Definition at line 1236 of file SystemBase.h.
range_m
template<class T> std::set<float> SystemBase< T >::range_m protected
Definition at line 1237 of file SystemBase.h.
range_n
template<class T> std::set<int> SystemBase< T >::range_n protected
Definition at line 1236 of file SystemBase.h.
states
template<class T> states_set<T>::type SystemBase< T >::states protected
Definition at line 1244 of file SystemBase.h.
Referenced by SystemBase< StateTwo >::add(), SystemBase< StateTwo >::applySchriefferWolffTransformation(), and SystemBase< StateTwo >::getConnections().
states_to_add
template<class T> std::set<T> SystemBase< T >::states_to_add protected
Definition at line 1238 of file SystemBase.h.
threshold_for_sqnorm
template<class T> double SystemBase< T >::threshold_for_sqnorm protected
Definition at line 1233 of file SystemBase.h.
The documentation for this class was generated from the following file:
/travis/pairinteraction/SystemBase.h