pairinteraction: HamiltonianTwo Class Reference
HamiltonianTwo Class Reference
#include <HamiltonianTwo.h>
Public Member Functions
HamiltonianTwo (const Configuration &config, boost::filesystem::path &path_cache, const std::shared_ptr< HamiltonianOne > &hamiltonian_one)
HamiltonianTwo (const Configuration &config, boost::filesystem::path &path_cache, std::shared_ptr< HamiltonianOne > hamiltonian_one1, std::shared_ptr< HamiltonianOne > hamiltonian_one2)
void calculate (const Configuration &conf_tot)
Public Member Functions inherited from Hamiltonian< BasisnamesTwo >
Hamiltonian ()=default
std::shared_ptr< Hamiltonianmatrix > get (size_t idx)
std::shared_ptr< const Hamiltonianmatrix > get (size_t idx) const
std::shared_ptr< const Configuration > getParams (size_t idx) const
size_t size () const
std::shared_ptr< const BasisnamesTwo > names () const
void removeUnnecessaryStates (std::vector< bool > &necessary)
Additional Inherited Members
Protected Attributes inherited from Hamiltonian< BasisnamesTwo >
std::vector< std::shared_ptr< Hamiltonianmatrix > > matrix_diag
std::vector< std::string > matrix_path
std::vector< std::shared_ptr< Configuration > > params
std::shared_ptr< BasisnamesTwo > basis
Detailed Description
Definition at line 40 of file HamiltonianTwo.h.
Constructor & Destructor Documentation
HamiltonianTwo() [1/2]
HamiltonianTwo::HamiltonianTwo (const Configuration & config, boost::filesystem::path & path_cache, const std::shared_ptr< HamiltonianOne > & hamiltonian_one)
Definition at line 26 of file HamiltonianTwo.cpp.
References calculate().
HamiltonianTwo() [2/2]
HamiltonianTwo::HamiltonianTwo (const Configuration & config, boost::filesystem::path & path_cache, std::shared_ptr< HamiltonianOne > hamiltonian_one1, std::shared_ptr< HamiltonianOne > hamiltonian_one2)
Definition at line 36 of file HamiltonianTwo.cpp.
References calculate().
Member Function Documentation
calculate()
void HamiltonianTwo::calculate (const Configuration & conf_tot)
Definition at line 47 of file HamiltonianTwo.cpp.
References Hamiltonian< BasisnamesTwo >::basis, Hamiltonianmatrix::basis(), Hamiltonianmatrix::changeBasis(), combine(), Hamiltonianmatrix::diagonalize(), energycutoff(), EVEN, StateTwoOld::first(), BasisnamesOne::fromFirst(), BasisnamesOne::fromSecond(), MatrixElements::getMultipole(), inverse_electric_constant, Symmetry::inversion, StateTwoOld::j, StateTwoOld::l, Hamiltonianmatrix::load(), Configuration::load_from_json(), StateTwoOld::m, Hamiltonian< BasisnamesTwo >::matrix_path, NA, Hamiltonianmatrix::num_basisvectors(), ODD, Symmetry::permutation, MatrixElements::precalculateMultipole(), sqlite::statement::prepare(), Symmetry::reflection, Hamiltonianmatrix::removeUnnecessaryBasisvectors(), Symmetry::rotation, Hamiltonianmatrix::save(), StateTwoOld::second(), and selectionRulesMultipole().
Referenced by HamiltonianTwo().
The documentation for this class was generated from the following files:
/travis/pairinteraction/HamiltonianTwo.h
/travis/pairinteraction/HamiltonianTwo.cpp