pairinteraction: /travis/pairinteraction/Hamiltonianmatrix.cpp File Reference
Hamiltonianmatrix.cpp File Reference
#include "Hamiltonianmatrix.h"
#include <stdexcept>
#include <boost/format.hpp>
Functions
Hamiltonianmatrix operator+ (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
Hamiltonianmatrix operator- (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
Hamiltonianmatrix operator* (const scalar_t &lhs, Hamiltonianmatrix rhs)
Hamiltonianmatrix operator* (Hamiltonianmatrix lhs, const scalar_t &rhs)
Hamiltonianmatrix combine (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, const std::shared_ptr< BasisnamesTwo > &basis_two, const Symmetry &sym)
void energycutoff (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, std::vector< bool > &necessary)
Function Documentation
combine()
Hamiltonianmatrix combine (const Hamiltonianmatrix & lhs, const Hamiltonianmatrix & rhs, const double & deltaE, const std::shared_ptr< BasisnamesTwo > & basis_two, const Symmetry & sym)
Definition at line 480 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::addBasis(), Hamiltonianmatrix::addEntries(), Hamiltonianmatrix::basis(), Hamiltonianmatrix::compress(), Hamiltonianmatrix::entries(), EVEN, Symmetry::inversion, NA, Hamiltonianmatrix::num_basisvectors(), Hamiltonianmatrix::num_coordinates(), ODD, Symmetry::permutation, Symmetry::reflection, and Symmetry::rotation.
Referenced by HamiltonianTwo::calculate().
energycutoff()
void energycutoff (const Hamiltonianmatrix & lhs, const Hamiltonianmatrix & rhs, const double & deltaE, std::vector< bool > & necessary)
Definition at line 710 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::basis(), Hamiltonianmatrix::entries(), and Hamiltonianmatrix::num_coordinates().
Referenced by HamiltonianTwo::calculate().
operator*() [1/2]
Hamiltonianmatrix operator* (const scalar_t & lhs, Hamiltonianmatrix rhs)
Definition at line 257 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::bytes, and Hamiltonianmatrix::entries_.
operator*() [2/2]
Hamiltonianmatrix operator* (Hamiltonianmatrix lhs, const scalar_t & rhs)
Definition at line 263 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::bytes, and Hamiltonianmatrix::entries_.
operator+()
Hamiltonianmatrix operator+ (Hamiltonianmatrix lhs, const Hamiltonianmatrix & rhs)
Definition at line 245 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::bytes, and Hamiltonianmatrix::entries_.
operator-()
Hamiltonianmatrix operator- (Hamiltonianmatrix lhs, const Hamiltonianmatrix & rhs)
Definition at line 251 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix::bytes, and Hamiltonianmatrix::entries_.