pairinteraction: /travis/pairinteraction/MatrixElementCache.h File Reference
MatrixElementCache.h File Reference
#include "Basisnames.h"
#include "State.h"
#include "Wavefunction.h"
#include "dtypes.h"
#include "utils.h"
#include <boost/filesystem.hpp>
#include <boost/functional/hash.hpp>
#include <boost/serialization/unordered_map.hpp>
#include <boost/serialization/unordered_set.hpp>
#include <wignerSymbols/wignerSymbols-cpp.h>
#include <memory>
#include <sstream>
#include <string>
#include <tuple>
#include <unordered_map>
Data Structures
class MatrixElementCache
Functions
bool selectionRulesMomentumNew (StateOne const &state1, StateOne const &state2, int q)
bool selectionRulesMomentumNew (StateOne const &state1, StateOne const &state2)
bool selectionRulesMultipoleNew (StateOne const &state1, StateOne const &state2, int kappa, int q)
bool selectionRulesMultipoleNew (StateOne const &state1, StateOne const &state2, int kappa)
Function Documentation
selectionRulesMomentumNew() [1/2]
bool selectionRulesMomentumNew (StateOne const & state1, StateOne const & state2, int q)
Definition at line 34 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
Referenced by SystemOne::initializeInteraction(), and MatrixElementCache::precalculateDiamagnetism().
selectionRulesMomentumNew() [2/2]
bool selectionRulesMomentumNew (StateOne const & state1, StateOne const & state2)
Definition at line 42 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
selectionRulesMultipoleNew() [1/2]
bool selectionRulesMultipoleNew (StateOne const & state1, StateOne const & state2, int kappa, int q)
Definition at line 49 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
Referenced by SystemTwo::initializeInteraction(), SystemOne::initializeInteraction(), and MatrixElementCache::precalculateDiamagnetism().
selectionRulesMultipoleNew() [2/2]
bool selectionRulesMultipoleNew (StateOne const & state1, StateOne const & state2, int kappa)
Definition at line 61 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().