pairinteraction: /travis/pairinteraction/unit_test/quantum_defect_test.cpp File Reference
quantum_defect_test.cpp File Reference
#include "EmbeddedDatabase.h"
#include "QuantumDefect.h"
#include "SQLite.h"
#include <boost/test/unit_test.hpp>
Macros
#define BOOST_TEST_MODULE Quantum defect test
Functions
BOOST_AUTO_TEST_CASE (qd_test)
BOOST_AUTO_TEST_CASE (qd_errors)
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE Quantum defect test
Definition at line 23 of file quantum_defect_test.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (qd_test)
Definition at line 26 of file quantum_defect_test.cpp.
References QuantumDefect::a1, QuantumDefect::a2, QuantumDefect::a3, QuantumDefect::a4, QuantumDefect::ac, sqlite::statement::get(), QuantumDefect::j, QuantumDefect::l, QuantumDefect::n, sqlite::statement::prepare(), QuantumDefect::rc, sqlite::statement::set(), QuantumDefect::species, sqlite::statement::step(), and QuantumDefect::Z.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (qd_errors)
Definition at line 63 of file quantum_defect_test.cpp.