pairinteraction: /travis/pairinteraction/unit_test/wavefunction_test.cpp File Reference
wavefunction_test.cpp File Reference
#include "QuantumDefect.h"
#include "SQLite.h"
#include "Wavefunction.h"
#include <boost/mpl/list.hpp>
#include <boost/test/unit_test.hpp>
#include <iostream>
Data Structures
struct Fixture< l >
Macros
#define BOOST_TEST_MODULE Wavefunctions test
Typedefs
typedef boost::mpl::list< Fixture< 1 >, Fixture< 2 > > Fixtures
Functions
BOOST_FIXTURE_TEST_CASE_TEMPLATE (model_potentials, T, Fixtures, T)
BOOST_FIXTURE_TEST_CASE_TEMPLATE (numerovs_method, T, Fixtures, T)
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE Wavefunctions test
Definition at line 23 of file wavefunction_test.cpp.
Typedef Documentation
Fixtures
typedef boost::mpl::list<Fixture<1>, Fixture<2> > Fixtures
Definition at line 35 of file wavefunction_test.cpp.
Function Documentation
BOOST_FIXTURE_TEST_CASE_TEMPLATE() [1/2]
BOOST_FIXTURE_TEST_CASE_TEMPLATE (model_potentials , T , Fixtures , T)
Definition at line 37 of file wavefunction_test.cpp.
References model_potential::g(), and model_potential::V().
Referenced by BOOST_FIXTURE_TEST_CASE_TEMPLATE().
BOOST_FIXTURE_TEST_CASE_TEMPLATE() [2/2]
BOOST_FIXTURE_TEST_CASE_TEMPLATE (numerovs_method , T , Fixtures , T)
Definition at line 44 of file wavefunction_test.cpp.
References BOOST_FIXTURE_TEST_CASE_TEMPLATE(), Numerov::integrate(), and Whittaker::integrate().